"""empty message

Revision ID: 218f78ffe1d5
Revises: c288aac4b342
Create Date: 2026-03-08 10:35:46.970921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218f78ffe1d5'
down_revision: Union[str, Sequence[str], None] = 'c288aac4b342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_members_chat_id_idx'), table_name='chat_members')
    op.drop_index(op.f('chat_members_user_id_idx'), table_name='chat_members')
    op.create_index(op.f('ix_chat_members_user_id'), 'chat_members', ['user_id'], unique=False)
    op.drop_index(op.f('message_reads_message_id_idx'), table_name='message_reads')
    op.create_index('idx_chat_created_at', 'messages', ['chat_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_last_active'), 'user_sessions', ['last_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_last_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('idx_chat_created_at', table_name='messages')
    op.create_index(op.f('message_reads_message_id_idx'), 'message_reads', ['message_id'], unique=False)
    op.drop_index(op.f('ix_chat_members_user_id'), table_name='chat_members')
    op.create_index(op.f('chat_members_user_id_idx'), 'chat_members', ['user_id'], unique=False)
    op.create_index(op.f('chat_members_chat_id_idx'), 'chat_members', ['chat_id'], unique=False)
    # ### end Alembic commands ###
