"""setup_clean_database

Revision ID: 3b50308c8511
Revises: 59e113188a86
Create Date: 2026-03-08 07:38:07.543305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b50308c8511'
down_revision: Union[str, Sequence[str], None] = '59e113188a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_device_session_uc', 'user_sessions', ['user_id', 'device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_device_session_uc', 'user_sessions', type_='unique')
    # ### end Alembic commands ###
