"""Remove redundant unique constraint from chat_members

Revision ID: 688543bbb963
Revises: d75dd533fe94
Create Date: 2026-03-04 22:45:48.883399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688543bbb963'
down_revision: Union[str, Sequence[str], None] = 'd75dd533fe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_chat_user_uc'), 'chat_members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('_chat_user_uc'), 'chat_members', ['chat_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
