"""empty message

Revision ID: 7870cb868daf
Revises: 218f78ffe1d5
Create Date: 2026-03-08 10:39:52.944337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7870cb868daf'
down_revision: Union[str, Sequence[str], None] = '218f78ffe1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_blocker_blocked', 'user_blocks', ['blocker_id', 'blocked_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blocker_blocked', table_name='user_blocks')
    # ### end Alembic commands ###
