"""Add bio and media dimensions

Revision ID: 81fb53e70346
Revises: cb1ab230275f
Create Date: 2026-03-04 11:02:11.987993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81fb53e70346'
down_revision: Union[str, Sequence[str], None] = 'cb1ab230275f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blocker_id', sa.String(), nullable=True),
    sa.Column('blocked_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='_blocker_blocked_uc')
    )
    op.create_index(op.f('ix_user_blocks_blocked_id'), 'user_blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_user_blocks_blocker_id'), 'user_blocks', ['blocker_id'], unique=False)
    op.create_index(op.f('ix_user_blocks_id'), 'user_blocks', ['id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fcm_token', name='_user_fcm_token_uc')
    )
    op.create_index(op.f('ix_user_devices_fcm_token'), 'user_devices', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.create_unique_constraint('_chat_user_uc', 'chat_members', ['chat_id', 'user_id'])
    op.drop_constraint(op.f('chat_members_chat_id_fkey'), 'chat_members', type_='foreignkey')
    op.drop_constraint(op.f('chat_members_user_id_fkey'), 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'chat_rooms', ['chat_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('media_width', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('media_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_height')
    op.drop_column('messages', 'media_width')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key(op.f('chat_members_user_id_fkey'), 'chat_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_members_chat_id_fkey'), 'chat_members', 'chat_rooms', ['chat_id'], ['id'])
    op.drop_constraint('_chat_user_uc', 'chat_members', type_='unique')
    op.create_table('devices',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('devices_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('devices_pkey'))
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_fcm_token'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_user_blocks_id'), table_name='user_blocks')
    op.drop_index(op.f('ix_user_blocks_blocker_id'), table_name='user_blocks')
    op.drop_index(op.f('ix_user_blocks_blocked_id'), table_name='user_blocks')
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
