"""final_merge_sessions_and_devices

Revision ID: c288aac4b342
Revises: 3b50308c8511
Create Date: 2026-03-08 07:53:40.941605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c288aac4b342'
down_revision: Union[str, Sequence[str], None] = '3b50308c8511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_devices_fcm_token'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.add_column('user_sessions', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('platform', sa.String(), nullable=True))
    op.drop_constraint(op.f('_user_device_session_uc'), 'user_sessions', type_='unique')
    op.create_unique_constraint('_user_single_session_uc', 'user_sessions', ['user_id'])
    op.create_index(op.f('ix_user_sessions_fcm_token'), 'user_sessions', ['fcm_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_fcm_token'), table_name='user_sessions')
    op.drop_constraint('_user_single_session_uc', 'user_sessions', type_='unique')
    op.create_unique_constraint(op.f('_user_device_session_uc'), 'user_sessions', ['user_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_sessions', 'platform')
    op.drop_column('user_sessions', 'fcm_token')
    op.create_table('user_devices',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fcm_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_devices_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_devices_pkey')),
    sa.UniqueConstraint('user_id', 'fcm_token', name=op.f('_user_fcm_token_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_fcm_token'), 'user_devices', ['fcm_token'], unique=False)
    # ### end Alembic commands ###
