"""Add delivered_at to message_read

Revision ID: cb1ab230275f
Revises: 30924538af57
Create Date: 2026-03-03 18:55:12.137614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1ab230275f'
down_revision: Union[str, Sequence[str], None] = '30924538af57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_reads', sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_reads', 'delivered_at')
    # ### end Alembic commands ###
