"""add_performance_indices

Revision ID: df4c9cfed749
Revises: 7870cb868daf
Create Date: 2026-03-08 11:23:35.474415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4c9cfed749'
down_revision: Union[str, Sequence[str], None] = '7870cb868daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_members_chat_id'), 'chat_members', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_reads_message_id'), 'message_reads', ['message_id'], unique=False)
    op.drop_constraint(op.f('message_reads_message_id_fkey'), 'message_reads', type_='foreignkey')
    op.drop_constraint(op.f('message_reads_user_id_fkey'), 'message_reads', type_='foreignkey')
    op.create_foreign_key(None, 'message_reads', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_reads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_reads', type_='foreignkey')
    op.drop_constraint(None, 'message_reads', type_='foreignkey')
    op.create_foreign_key(op.f('message_reads_user_id_fkey'), 'message_reads', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('message_reads_message_id_fkey'), 'message_reads', 'messages', ['message_id'], ['id'])
    op.drop_index(op.f('ix_message_reads_message_id'), table_name='message_reads')
    op.drop_index(op.f('ix_chat_members_chat_id'), table_name='chat_members')
    # ### end Alembic commands ###
